[build]
  base = "src/frontend"
  command = "pnpm turbo build && pnpm --filter=web next export"
  publish = "apps/web/out" 
  functions = "apps/web/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22"    # 22 대신 20 사용 (안정 버전)

# Next.js 앱을 위한 리다이렉트 규칙
[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"