[build]
  base = "src/frontend/apps/web"
  command = "pnpm build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../../"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

