[build]
  base = "src/frontend"
  command = "pnpm turbo build"
  publish = "apps/web/.next/standalone" 
  functions = "apps/web/.next/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next" 
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
