server:
  port: ${AUTH_PORT}

spring:
  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}

kakao:
  clientId: ${KAKAO_CLIENTID}

default_image: ${DEFAULT_IMAGE_S3}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
